// <auto-generated />
namespace MyForum.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class cascaderequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascaderequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071738596_cascade required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
